export enum RoomEventName {
  FORMATION_SELECTION_STARTED = 'FORMATION_SELECTION_STARTED',
  PLAYER_SELECTED_FORMATION = 'PLAYER_SELECTED_FORMATION',
  ALL_FORMATIONS_SELECTED = 'ALL_FORMATIONS_SELECTED',
  DRAFT_READY = 'DRAFT_READY',
  DRAFT_PLAYER_READY = 'DRAFT_PLAYER_READY',
  DRAFT_COMPLETE = 'DRAFT_COMPLETE',
  COACH_SELECTION_STARTED = 'COACH_SELECTION_STARTED',
  PLAYER_SELECTED_COACH = 'PLAYER_SELECTED_COACH',
  ALL_COACHES_SELECTED = 'ALL_COACHES_SELECTED',
  TEAMS_READY = 'TEAMS_READY',
  LEAGUE_READY = 'LEAGUE_READY',
  MATCH_STARTED = 'MATCH_STARTED',
  MATCH_MINUTE_UPDATED = 'MATCH_MINUTE_UPDATED',
  MATCH_EVENT_CREATED = 'MATCH_EVENT_CREATED',
  BALL_MOVED = 'BALL_MOVED',
  ATTACK_STARTED = 'ATTACK_STARTED',
  ATTACK_PROGRESS = 'ATTACK_PROGRESS',
  SHOT = 'SHOT',
  GOAL = 'GOAL',
  MOMENTUM_CHANGED = 'MOMENTUM_CHANGED',
  MATCH_FINISHED = 'MATCH_FINISHED',
  GOAL_SCORED = 'GOAL_SCORED',
  HALF_TIME = 'HALF_TIME',
  FULL_TIME = 'FULL_TIME',
  LEAGUE_TABLE_UPDATED = 'LEAGUE_TABLE_UPDATED',
  LEAGUE_COMPLETED = 'LEAGUE_COMPLETED',
  LOBBY_RESET = 'LOBBY_RESET',
  CHAT_MESSAGE = 'CHAT_MESSAGE',
}

export interface RoomEventPayload {
  readonly lobbyCode: string;
  readonly phase: string;
  readonly formationSelectedCount?: number;
  readonly participantCount?: number;
  readonly participantId?: string;
  readonly formationId?: string;
  readonly coachId?: string;
  readonly coachSelectedCount?: number;
  readonly draftSessionId?: string;
  readonly matchId?: string;
  readonly currentMinute?: number;
  readonly homeScore?: number;
  readonly awayScore?: number;
  readonly eventId?: string;
  readonly eventType?: string;
  readonly commentary?: string;
  readonly ballZone?: string;
  readonly previousBallZone?: string;
  readonly homeMomentum?: number;
  readonly awayMomentum?: number;
  readonly attackChainId?: string;
  readonly winnerDisplayName?: string;
  readonly winnerParticipantId?: string;
  readonly messageId?: string;
  readonly displayName?: string;
  readonly body?: string;
  readonly sentAt?: string;
}
