/** Canonical nationality key (uppercase) → Turkish display name. */
export const NATIONALITY_DISPLAY_TR: Readonly<Record<string, string>> = {
  AFGHANISTAN: 'Afganistan',
  ALBANIA: 'Arnavutluk',
  ALGERIA: 'Cezayir',
  ANDORRA: 'Andorra',
  ANGOLA: 'Angola',
  ARGENTINA: 'Arjantin',
  ARMENIA: 'Ermenistan',
  AUSTRALIA: 'Avustralya',
  AUSTRIA: 'Avusturya',
  AZERBAIJAN: 'Azerbaycan',
  BAHRAIN: 'Bahreyn',
  BELARUS: 'Belarus',
  BELGIUM: 'Belçika',
  BENIN: 'Benin',
  BOLIVIA: 'Bolivya',
  'BOSNIA-HERZEGOVINA': 'Bosna Hersek',
  BRAZIL: 'Brezilya',
  BULGARIA: 'Bulgaristan',
  'BURKINA FASO': 'Burkina Faso',
  BURUNDI: 'Burundi',
  CAMEROON: 'Kamerun',
  CANADA: 'Kanada',
  'CAPE VERDE': 'Yeşil Burun Adaları',
  'CENTRAL AFRICAN REPUBLIC': 'Orta Afrika Cumhuriyeti',
  CHAD: 'Çad',
  CHILE: 'Şili',
  CHINA: 'Çin',
  COLOMBIA: 'Kolombiya',
  COMOROS: 'Komorlar',
  CONGO: 'Kongo',
  'COSTA RICA': 'Kosta Rika',
  'COTE D IVOIRE': 'Fildişi Sahili',
  "COTE D'IVOIRE": 'Fildişi Sahili',
  CROATIA: 'Hırvatistan',
  CUBA: 'Küba',
  CURACAO: 'Curaçao',
  CYPRUS: 'Kıbrıs',
  'CZECH REPUBLIC': 'Çekya',
  CZECHIA: 'Çekya',
  DENMARK: 'Danimarka',
  'DOMINICAN REPUBLIC': 'Dominik Cumhuriyeti',
  'DR CONGO': 'Kongo DC',
  ECUADOR: 'Ekvador',
  EGYPT: 'Mısır',
  ENGLAND: 'İngiltere',
  'EQUATORIAL GUINEA': 'Ekvator Ginesi',
  ESTONIA: 'Estonya',
  ETHIOPIA: 'Etiyopya',
  'FAROE ISLANDS': 'Faroe Adaları',
  FINLAND: 'Finlandiya',
  FRANCE: 'Fransa',
  'FRENCH GUIANA': 'Fransız Guyanası',
  GABON: 'Gabon',
  GAMBIA: 'Gambiya',
  GEORGIA: 'Gürcistan',
  GERMANY: 'Almanya',
  GHANA: 'Gana',
  GREECE: 'Yunanistan',
  GUADELOUPE: 'Guadeloupe',
  GUATEMALA: 'Guatemala',
  GUINEA: 'Gine',
  'GUINEA-BISSAU': 'Gine-Bissau',
  HAITI: 'Haiti',
  HONDURAS: 'Honduras',
  HUNGARY: 'Macaristan',
  ICELAND: 'İzlanda',
  INDIA: 'Hindistan',
  INDONESIA: 'Endonezya',
  IRAN: 'İran',
  IRAQ: 'Irak',
  IRELAND: 'İrlanda',
  ISRAEL: 'İsrail',
  ITALY: 'İtalya',
  'IVORY COAST': 'Fildişi Sahili',
  JAMAICA: 'Jamaika',
  JAPAN: 'Japonya',
  JORDAN: 'Ürdün',
  KAZAKHSTAN: 'Kazakistan',
  KENYA: 'Kenya',
  KOSOVO: 'Kosova',
  'KOREA SOUTH': 'Güney Kore',
  'KOREA, SOUTH': 'Güney Kore',
  LATVIA: 'Letonya',
  LEBANON: 'Lübnan',
  LIBERIA: 'Liberya',
  LIBYA: 'Libya',
  LITHUANIA: 'Litvanya',
  LUXEMBOURG: 'Lüksemburg',
  MADAGASCAR: 'Madagaskar',
  MALAWI: 'Malavi',
  MALAYSIA: 'Malezya',
  MALI: 'Mali',
  MALTA: 'Malta',
  MAURITANIA: 'Moritanya',
  MEXICO: 'Meksika',
  MOLDOVA: 'Moldova',
  MONTENEGRO: 'Karadağ',
  MOROCCO: 'Fas',
  MOZAMBIQUE: 'Mozambik',
  NETHERLANDS: 'Hollanda',
  'NEW ZEALAND': 'Yeni Zelanda',
  NICARAGUA: 'Nikaragua',
  NIGER: 'Nijer',
  NIGERIA: 'Nijerya',
  'NORTH MACEDONIA': 'Kuzey Makedonya',
  'NORTHERN IRELAND': 'Kuzey İrlanda',
  NORWAY: 'Norveç',
  PANAMA: 'Panama',
  PARAGUAY: 'Paraguay',
  PERU: 'Peru',
  PHILIPPINES: 'Filipinler',
  POLAND: 'Polonya',
  PORTUGAL: 'Portekiz',
  'PUERTO RICO': 'Porto Riko',
  QATAR: 'Katar',
  ROMANIA: 'Romanya',
  RUSSIA: 'Rusya',
  'SAUDI ARABIA': 'Suudi Arabistan',
  SCOTLAND: 'İskoçya',
  SENEGAL: 'Senegal',
  SERBIA: 'Sırbistan',
  'SIERRA LEONE': 'Sierra Leone',
  SLOVAKIA: 'Slovakya',
  SLOVENIA: 'Slovenya',
  'SOUTH AFRICA': 'Güney Afrika',
  'SOUTH KOREA': 'Güney Kore',
  SPAIN: 'İspanya',
  SURINAME: 'Surinam',
  SWEDEN: 'İsveç',
  SWITZERLAND: 'İsviçre',
  SYRIA: 'Suriye',
  TANZANIA: 'Tanzanya',
  THAILAND: 'Tayland',
  TOGO: 'Togo',
  'TRINIDAD AND TOBAGO': 'Trinidad ve Tobago',
  'THE GAMBIA': 'Gambiya',
  TUNISIA: 'Tunus',
  TURKEY: 'Türkiye',
  TURKIYE: 'Türkiye',
  TÜRKIYE: 'Türkiye',
  UKRAINE: 'Ukrayna',
  'UNITED STATES': 'ABD',
  URUGUAY: 'Uruguay',
  UZBEKISTAN: 'Özbekistan',
  VENEZUELA: 'Venezuela',
  WALES: 'Galler',
  ZAMBIA: 'Zambiya',
  ZIMBABWE: 'Zimbabve',
};

/** Alternate spellings from providers → canonical map key. */
export const NATIONALITY_KEY_ALIASES: Readonly<Record<string, string>> = {
  "COTE D'IVOIRE": 'COTE D IVOIRE',
  'CÔTE D IVOIRE': 'COTE D IVOIRE',
  'CONGO DR': 'DR CONGO',
  'DEMOCRATIC REPUBLIC OF THE CONGO': 'DR CONGO',
  'KOREA, SOUTH': 'KOREA SOUTH',
  'KOREA SOUTH': 'KOREA SOUTH',
  'THE GAMBIA': 'GAMBIA',
  'CÔTE DIVOIRE': 'COTE D IVOIRE',
};
