export const DataQualityIssueCode = {
  MISSING_MARKET_VALUE: 'MISSING_MARKET_VALUE',
  MISSING_POSITION: 'MISSING_POSITION',
  MISSING_AGE: 'MISSING_AGE',
  MISSING_IMAGE: 'MISSING_IMAGE',
  MISSING_CLUB: 'MISSING_CLUB',
  MISSING_COMPETITION: 'MISSING_COMPETITION',
  DUPLICATE_PROVIDER_EXTERNAL_ID: 'DUPLICATE_PROVIDER_EXTERNAL_ID',
  INVALID_MARKET_VALUE: 'INVALID_MARKET_VALUE',
} as const;

export type DataQualityIssueCode = (typeof DataQualityIssueCode)[keyof typeof DataQualityIssueCode];
